services:
    app:
        build:
            context: .
            args:
                uid: 1000
            dockerfile: docker/dev/app/Dockerfile
            target: app-dev
        image: loadorderlibrary-next:dev
        container_name: lol-next-app
        restart: unless-stopped
        ports:
            - '127.0.0.1:8002:3000'
        networks:
            - lol-next

networks:
    lol-next:
        driver: bridge
