services:
    app:
        image: ghcr.io/phinocio/loadorderlibrary-frontend:main
        env_file: .env
        container_name: lol-frontend-app
        restart: unless-stopped
        ports:
            - '127.0.0.1:8000:3000'
        networks:
            - lol

networks:
    lol:
        external: true
