services:
    app:
        build:
            context: .
            args:
                uid: 1000
            dockerfile: docker/dev/app/Dockerfile
            target: app-dev
        image: loadorderlibrary-frontend:dev
        container_name: lol-frontend-app
        restart: unless-stopped
        ports:
            - '0.0.0.0:5173:3000'
        networks:
            - lol-next

networks:
    lol-next:
        driver: bridge
